apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d0mq7xp0v-nodejs
  janus-idp.io/tekton: d0mq7xp0v-nodejs
  backstage.io/kubernetes-id: d0mq7xp0v-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d0mq7xp0v-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
